### ISSUE TITLE
BatchCluster : An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by rolanday** [photostructure/exiftool-vendored.js#68]
After updating to v9.3.1, tsc is complaining about accessors being declared in ambient context. Was previously on v9.1.0. The offending component is BatchCluster (v5.9.0), which if I forcibly revert to 5.7.1, then appears to be OK.

Any ideas? Thanks!

----- tsc output

node_modules/batch-cluster/dist/BatchCluster.d.ts:53:9 - error TS1086: An accessor cannot be declared in an ambient context.

53     get ended(): boolean;
           ~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:70:9 - error TS1086: An accessor cannot be declared in an ambient context.

70     get isIdle(): boolean;
           ~~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:74:9 - error TS1086: An accessor cannot be declared in an ambient context.

74     get pendingTasks(): number;
           ~~~~~~~~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:78:9 - error TS1086: An accessor cannot be declared in an ambient context.

78     get meanTasksPerProc(): number;
           ~~~~~~~~~~~~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:82:9 - error TS1086: An accessor cannot be declared in an ambient context.

82     get spawnedProcs(): number;
           ~~~~~~~~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:86:9 - error TS1086: An accessor cannot be declared in an ambient context.

86     get busyProcs(): number;
           ~~~~~~~~~

node_modules/batch-cluster/dist/BatchCluster.d.ts:90:9 - error TS1086: An accessor cannot be declared in an ambient context.

90     get internalErrorCount(): number;
           ~~~~~~~~~~~~~~~~~~

node_modules/batch-cluster/dist/Deferred.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get pending(): boolean;
           ~~~~~~~

node_modules/batch-cluster/dist/Deferred.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get fulfilled(): boolean;
           ~~~~~~~~~

node_modules/batch-cluster/dist/Deferred.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get rejected(): boolean;
           ~~~~~~~~

node_modules/batch-cluster/dist/Task.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get promise(): Promise<T>;
           ~~~~~~~

node_modules/batch-cluster/dist/Task.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     get pending(): boolean;
           ~~~~~~~

node_modules/batch-cluster/dist/Task.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     get state(): string;
           ~~~~~

node_modules/batch-cluster/dist/Task.d.ts:30:9 - error TS1086: An accessor cannot be declared in an ambient context.

30     get stdout(): string;
           ~~~~~~

node_modules/batch-cluster/dist/Task.d.ts:31:9 - error TS1086: An accessor cannot be declared in an ambient context.

31     get stderr(): string;
           ~~~~~~


Found 15 errors.

**Comment by rolanday** [comment]
Closing this issue. Discovered the following page after finding issue: 
https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#get-and-set-accessors-allowed-in-ambient-contexts


> As a result, users can write getters and setters in ambient contexts in TypeScript 3.6.
> 
> declare class Foo {
>     // Allowed in 3.6+.
>     get x(): number;
>     set x(val: number): void;
> }
> In TypeScript 3.7, the compiler itself will take advantage of this feature so that generated .d.ts files will also emit get/set accessors.

After updating to typescript v3.7.2, issue is resolved.
